### ISSUE TITLE
IndeedApi#Bug

### ISSUE THREAD

**Issue by db0sch** [db0sch/drip#13]
Got this error message: 
NoMethodError: undefined method `jobkey' for nil:NilClass
	from /home/dbo/code/db0sch/drip/app/services/indeed_api.rb:66:in `update_infos'
	from /home/dbo/code/db0sch/drip/app/services/indeed_api.rb:26:in `block in get_jobs'
	from /home/dbo/code/db0sch/drip/app/services/indeed_api.rb:26:in `each'
	from /home/dbo/code/db0sch/drip/app/services/indeed_api.rb:26:in `get_jobs'
	from (irb):5

must be resolved before working on the rest.
really need to do some testing on this service.

**Comment by db0sch** [comment]
In fact, the array containing all the job offers that were sent to update_infos, contained some nil (when a job_offer already exists, it stores a nil).
Therefore, an error was thrown when a nil went into update_infos.

Need to rething what is return into this array.

For the moment, i just call .compact on array to reject nil class before going to update_info.
